export const PROJECTDETAILS = "PROJECTDETAILS";
export const CLIENTDETAILS = "CLIENTDETAILS";
export const PROJECTFILTER = "PROJECTFILTER";
export const CLIENTFILTER = "CLIENTFILTER";
export const REFRESH = "REFRESH";
